### ISSUE TITLE
Change repo name - or delete!

### ISSUE THREAD

**Issue by lakruzz** [Praqma/pretested-integration#2]
Hi @Andrey9kin 

What's the story about this repo?

1) There's noting in it
2) It's name clashing (sematically at least) with [Pretested Integration Plugin](https://github.com/Praqma/pretested-integration-plugin)

Could it be either deleted or renamed?

**Comment by buep** [comment]
We discussed in a JOSRA meetings some weeks back... it is a script based implementation of PIP. I think it fits fine, if it have the same workflows and works the same way as PIP.

The README acutally also explains it - but I would very much like there to be some content, instead of just an empty repo. See #1

**Comment by lakruzz** [comment]
OK, so the actual scriprt is missing, that can be fixed, right @andrey9kin?

But there is still something skewy abot the name. 

If, next time, we implement the same featue in TFS - what repo should that go to?

I vote that the name of the repo, should give insight, not just to the content (they should _all_ be named "pretested-integration" then)  but also the context

**Comment by buep** [comment]
Unless this repo is going to be the generic pretested integration thingy....as we talked about it could end up being instead of plugins etc.
But what-ever, a new name is also fine.

**Comment by Andrey9kin** [comment]
@lakruzz @buep I see it as a collection of scripts adapted for all CI engines we use. So in this way, it will be generic. For now, it is only Travis, but nothing stops us from adding more as soon as we know how to do it for other systems.

If you still want me to rename it then please suggest a new name

**Comment by buep** [comment]
I'm good with the name as I also see this repo as being the general one.

Maybe you can update the readme and point to our plugin, as an "jenkins implementation" - And maybe also to the plugin documentation, because there the workflows are described?

I link to this repo by the way from my code-utils repo: https://github.com/Praqma/code-utils#pretested-integration

**Comment by Andrey9kin** [comment]
@buep fixed. anything else?

**Comment by buep** [comment]
No, I'm good - it is cool to have it as a script also.

**Comment by JKrag** [comment]
I would suggest renaming to "git-phlow-scripts" or similar. Isn't "Git-phlow" the new name we use for what used to be called "Josra git flow" then "CoDe:U Git Flow"?  
If this is the "brand" for the concept, then Pretested-integration-plugin is just a Jenkins specific plugin suitable for implementing "Git Phlow" on Jenkins. Similar plugins for other platforms might also end up being named pretested, or might be called something else, depending on which missing puzzle piece the plugin solves on the platform in question.

Just my 5c...

**Comment by buep** [comment]
I see pretested-integration as a piece of the codeu git flow... and the recent write-up of our Pragmatic work flow blog post.
I can use pretested-integration without our way of working, thus it lives as an independent "product", while the code:u git flow requires the pretested integration to be used as a concept in the flow. But it doesn't have to use our script or plugin, just the concept. The way of working, can also be used with a dummy pretested integration step, that always is true.

So I will say you point is very good - how do these things bind together. It is time to set the lines straight and write a blog post about it.

That is not part of this issue. I'm posting it on slack, and closing this issue.
